from __future__ import annotations

BEST_MAX = 10
EXCELLENT_MAX = 30
INACCURACY_MIN = 80
MISTAKE_MIN = 120
BLUNDER_MIN = 200
SLOW_IN_BOOK_PCT = 0.10
BLUNDER_CLUSTER_WINDOW = 6
INSTANT_OUT_OF_BOOK_MAX_PLY = 10
REP_MOVE_FINE_MAX = 30
REP_MOVE_INACCURATE_MIN = 80
DEVIATION_WORSE_MIN = 50
